name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      -
jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Builds and Starts
        run: |
          docker-compose up -d
      - name: install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Selenium Side Runner
        run: |
          npm install -g selenium-side-runner
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
      - name: Install seleniumbase
        run: pip install seleniumbase
      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver
      - name: Run Tests
        run: |
         selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" post.side
      - name: Run Unit Tests
        run: |
          docker-compose up -d
          docker exec realworld_drash deno test -A --unstable tests/unit/models/base_model_test.ts

  linter:
      # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Formatter
        run: deno fmt --check --unstable --ignore='src/public,src/vue,src/package.json,src/webpack.config.js'

      - name: Linter
        run: deno lint --unstable --ignore='src/public,src/vue,src/package.json,src/webpack.config.js'
